import { FabricObject } from "fabric";
export declare module "fabricComponents" {
    export declare type ObjectRef = Pick<
        FabricObject,
        | "id"
        | "name"
        | "hideOnLayer"
        | "originX"
        | "originY"
        | "top"
        | "left"
        | "width"
        | "height"
        | "scaleX"
        | "scaleY"
        | "flipX"
        | "flipY"
        | "opacity"
        | "angle"
        | "skewX"
        | "skewY"
        | "hoverCursor"
        | "moveCursor"
        | "padding"
        | "borderColor"
        | "borderDashArray"
        | "cornerColor"
        | "cornerStrokeColor"
        | "cornerStyle"
        | "cornerDashArray"
        | "centeredScaling"
        | "centeredRotation"
        | "fill"
        | "fillRule"
        | "globalCompositeOperation"
        | "backgroundColor"
        | "selectionBackgroundColor"
        | "stroke"
        | "strokeWidth"
        | "strokeDashArray"
        | "strokeDashOffset"
        | "strokeLineCap"
        | "strokeLineJoin"
        | "strokeMiterLimit"
        | "shadow"
        | "borderScaleFactor"
        | "minScaleLimit"
        | "selectable"
        | "evented"
        | "visible"
        | "hasControls"
        | "hasBorders"
        | "perPixelTargetFind"
        | "includeDefaultValues"
        | "lockMovementX"
        | "lockMovementY"
        | "lockRotation"
        | "lockScalingX"
        | "lockScalingY"
        | "lockSkewingX"
        | "lockSkewingY"
        | "lockScalingFlip"
        | "excludeFromExport"
        | "objectCaching"
        | "noScaleCache"
        | "strokeUniform"
        | "dirty"
        | "paintFirst"
        | "activeOn"
        | "colorProperties"
        | "inverted"
        | "absolutePositioned"
        | "text"
        | "charSpacing"
        | "lineHeight"
        | "fontSize"
        | "fontWeight"
        | "fontFamily"
        | "fontStyle"
        | "pathSide"
        | "pathAlign"
        | "underline"
        | "overline"
        | "linethrough"
        | "textAlign"
        | "direction"
    > &
        Pick<Rect, "rx" | "ry">;
}

export declare interface Canvas {
    _objects: FabricObject[];
}
